### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by araichev** [manaakiwhenua/rhealpixdggs-py#14]
Hi folks, Alex Raichev here, original developer of rhealpixdggs-py.
Can you update me on the status and roadmap of this project?
I notice that no commits have been made in the past two years.

**Comment by rggibb** [comment]
Hi @araichev, great to hear from you. 

The code is getting used in its current state, but needs some significant activity to - in no particular order:
a) align it with the emerging [OGC API DGGS](https://ogcapi.ogc.org/dggs/) standard
b) provide additional language bindings
c) improve documentation
d) improve its performance
e) in general move the libraries towards main stream
f) extend the code to 3D and 4D .. in line with the current [OGC](https://docs.opengeospatial.org/as/20-040r3/20-040r3.pdf) & ifunctionally identical [ISO/TC211/19170-1](https://www.iso.org/standard/32588.html) standard

My personal focus since retiring has been to focus on evolving the standards, in the belief that would increase the adoption of DGGS and as a result the demand for DGGS libraries, and this is certainly happening & the need for work on this project is definitely there. There is a small community of active users - dominantly in Australia & Estonia who are have plans to extend the code.

**Comment by nicholascar** [comment]
Hi @araichev, great to have you still interested! Just flagging @recalcitrantsupplant into this thread too since he's worked on must of our DGGS implementation.

There is a final edit to the draft of the GeoSPARQL standard that is about presenting DGGS values as text in a Knowledge Graph that will soon be merged (https://github.com/opengeospatial/ogc-geosparql/pull/364/files) and then that standard will both implement a simple form of DGGS and reference AusPIX, as an rHealPix parametrisation, specifically.

I just mentioned to @rggibb that I'm doing spatial data system consulting to Australian governments and there is some DGGS interest there. I'm keen to meet soon to discuss this in general and the particular things Robert list above to specifically. Might be time for more students...

**Comment by recalcitrantsupplant** [comment]
Thanks Nick, Robert,

@araichev for context, here's a few DGGS related things I/we have worked on:

Drawing cells / cell collections - this was only intended to be for sanity checking of results http://dggsdraw.surroundaustralia.com/

https://github.com/surroundaustralia/rhealpix-geo and https://github.com/surroundaustralia/rhealpix-sf
Two python libraries. The first implements Cell/CellCollection python objects without any dependencies, and the latter uses these to provide spatial functions (contains, within etc.). There's a wrapped version of the spatial functions for RDFLib, a python library for working with RDF.

https://github.com/surroundaustralia/jena-dggs-geosparql
Cell/CellCollection objects in java, and spatial functions built on top of these, then wrapped as filter functions for Apache Jena, a triplestore. We used this library to demonstrate DGGS functions can be conformant to the GeoSPARQL standard.

In general I'm keen to see more performant conversion + implement a DGGS spatial index for a triplestore.

**Comment by araichev** [comment]
Hi @nicholascar and @recalcitrantsupplant , thanks for the DGGS update.
I'll explore the links you sent.
@nicholascar yes, let's chat.
I'll email you at the email address listed in your profile.

**Comment by alpha-beta-soup** [comment]
We have just released (v0.5.4)[https://github.com/manaakiwhenua/rhealpixdggs-py/releases/tag/0.5.4], the intention of which is a light-touch update to Python 3.11 to modernise the existing codebase before embarking on larger changes. We have a small internal roadmap and will seek to use Github to communicate this, as well as outstanding bugs, community support, etc.
